# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/peridot-miuicamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),peridot-miuicamera)

endif
