# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/peridot-camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/peridot-camera


PRODUCT_PACKAGES += \
    vendor.xiaomi.hardware.campostproc@1.0 \
    libMiStereoFactoryCalibAnalyzeBin_qual \
    libmiStereoCalibLib_qual \
    MIUIVideoPlayer \
    MiuixEditor_global \
    MIUIGalleryGlobal \
    MiuiCamera
